# - Setup file for Anaconda environments in support of the darksun package
# ! This file is temporary, during development will be substituted by a `project.toml` script

name: darksun

channels:
  - anaconda
  - conda-forge
  - defaults
#  - nvidia
#  - pytorch

# - these dependencies and their version may change during development
dependencies:
  - python=3.12
  - numpy=2.0.1
  - matplotlib=3.9.2
  - tqdm=4.67.1
  - scipy=1.14.1
  - pandas=2.2.2
  - astropy=7.0.0
  - reproject=0.14.1

# to add:
#   - bloodmoon
#   - scikit-learn
#   - pytorch=2.5.1
#   - pytorch-cuda=12.4